In [1]:
import tensorflow as tf

2024-04-28 18:42:15.562099: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-28 18:42:15.582510: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-28 18:42:15.582529: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-28 18:42:15.583060: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-28 18:42:15.587049: I tensorflow/core/platform/cpu_feature_guar

### Variables


Variables are tensors with fixed type and shape but their values can be changed through operations.


In [2]:
x = tf.constant([[1.0, 2.0]])

2024-04-28 18:42:32.550824: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-28 18:42:32.573859: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-28 18:42:32.573886: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-28 18:42:32.575933: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-28 18:42:32.575952: I external/local_xla/xla/stream_executor

In [3]:
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

We can create a variable from a tensor by calling `tf.Variable`


In [4]:
x_var = tf.Variable(x)

tf.Variable share attributes with tensors


In [5]:
x_var.shape

TensorShape([1, 2])

In [6]:
x_var.numpy()

array([[1., 2.]], dtype=float32)

### Gradient


`tf.Variable` allow us to calculate gradients


In [7]:
x = tf.Variable([[1.0, 2.0]])

We use the `tf.GradientTape` api to calculate the gradient of a function


In [8]:
with tf.GradientTape() as tape:
    y = x**2
    
    dy_dx = tape.gradient(y, x)

In [9]:
dy_dx.numpy()

array([[2., 4.]], dtype=float32)