In [2]:
import numpy as np
import tensorflow as tf

## tf.Tensor vs np.array


Tensors are a type of array used by Tensorflow. They have a lot in common with numpy arrays.


In [3]:
arr = np.array([[1, 2, 5], [5,7,3]])

In [4]:
arr

array([[1, 2, 5],
       [5, 7, 3]])

Convert a numpy array to a Tensorflow tensor with the following line:


In [6]:
tensor = tf.convert_to_tensor(arr)

Access the numpy array by using `.numpy()`


In [7]:
tensor.numpy()

array([[1, 2, 5],
       [5, 7, 3]])

Tensors and array share some attributes, such as shape.


In [8]:
arr.shape

(2, 3)

In [9]:
tensor.shape

TensorShape([2, 3])

## Operations on tensors


Similarly to np.arrays, we can perform operation on tensors.


In [10]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>

Element-wise multiplication


In [11]:
tensor*2

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 2,  4, 10],
       [10, 14,  6]])>

Broadcasting rules apply.


In [12]:
tensor*tf.constant([3, 2, 2], dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 3,  4, 10],
       [15, 14,  6]])>

## Additional attribute & methods


Find the tensor location


In [13]:
tensor.device

'/job:localhost/replica:0/task:0/device:GPU:0'

Move tensor to the gpu by calling `tensor.gpu()`


In [14]:

physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_visible_devices(physical_devices[0], 'GPU')


In [15]:
physical_devices

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [16]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [17]:
tf.debugging.set_log_device_placement(True)

# Create some tensors
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)

print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
